=== sahava/gtm-datalayer-test/lib/validTestConfSchema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "baseUrl": {
            "type": "string",
            "format": "uri"
        },
        "basePath": {
            "type": "string",
            "pattern": "^/"
        },
        "dataLayerName": {
            "type": "string"
        },
        "multipleContainers" : {
            "type" : "boolean"
        },
        "dataLayer": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/dataLayerObject"
            }
        },
        "page": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/pageObject"
            }
        }
    },
    "required": [
        "baseUrl",
        "basePath"
    ],
    "definitions": {
        "dataLayerObject": {
            "oneOf" : [{
                "type" : "object",
                "properties" : {
                    "@expect" : {
                        "type" : "string"
                    },
                    "@json" : {
                        "enum" : [false]
                    }
                }
            },{
                "type" : "object",
                "properties" : {
                    "@expect" : {
                        "type" : "string"
                    }
                },
                "additionalProperties" : {
                    "allOf" : [
                        {"$ref" : "http://json-schema.org/schema#"},
                        {"$ref" : "#/definitions/rootRequired"}
                    ],
                    "not" : {
                        "@json" : {
                            "enum" : [false]
                        }
                    }
                }
            }]
        },
        "pageObject": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string",
                    "pattern": "^/"
                },
                "dataLayer": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dataLayerObject"
                    }
                }
            },
            "additionalProperties": false,
            "required": [
                "path",
                "dataLayer"
            ]
        },
        "rootRequired": {
            "type" : "object",
            "properties" : {
                "@rootRequired" : {
                    "enum" : [false]
                }
            }
        }
    }
}

=== sahava/gtm-datalayer-test/spec/dataLayer/dataLayer.conf.json
{
    "baseUrl" : "http://localhost:8080",
    "basePath" : "/",
    "dataLayerName" : "dataLayer",
    "dataLayer" : [{
        "pageType" : {
            "type" : "string",
            "enum" : ["article", "main", "other"]
        },
        "pageCategory" : {
            "type" : "array",
            "items" : {
                "type" : "string",
                "enum" : ["biography", "review", "editorial", "column"]
            }
        },
        "user" : {
            "type" : "object",
            "properties" : {
                "logged-in" : {
                    "type" : "boolean"
                }
            }
        }
    }],
    "page" : [{
        "path" : "/",
        "dataLayer" : [{
            "@expect" : "dataLayer to have Enhanced Ecommerce Purchase payload",
            "ecommerce" : {
                "type" : "object",
                "properties" : {
                    "purchase" : {
                        "$ref" : "/enhancedEcommerceSchema.json#/definitions/purchase"
                    }
                },
                "required" : ["purchase"]
            }
        }]
    }]
}
